parameters:
    env(GEOIP_DIR): '%kernel.project_dir%/data/geoip'

services:
    Gupalo\GeoIp2\GeoIp:
        public: true
        arguments:
            - '@Gupalo\GeoIp2\MaxMindGeoIp'
            - '@Gupalo\GeoIp2\Ip2LocationGeoIp'

    Gupalo\GeoIp2\MaxMindGeoIp:
        public: true
        arguments: [ '%env(resolve:GEOIP_DIR)%' ]

    Gupalo\GeoIp2\Ip2LocationGeoIp:
        public: true
        arguments: [ '%env(resolve:GEOIP_DIR)%' ]

    Gupalo\GeoIp2\Twig\GeoIpExtension:
        public: true
        tags: [ 'twig.extension' ]
        arguments: [ '@Gupalo\GeoIp2\GeoIp' ]
