parameters:
    env(GEOIP_DIR): '%kernel.project_dir%/data/geoip'

services:
    Gupalo\GeoIp\GeoIp:
        public: true
        arguments:
            - '@Gupalo\GeoIp\MaxMindGeoIp'
            - '@Gupalo\GeoIp\Ip2LocationGeoIp'

    Gupalo\GeoIp\MaxMindGeoIp:
        public: true
        arguments: [ '%env(resolve:GEOIP_DIR)%' ]

    Gupalo\GeoIp\Ip2LocationGeoIp:
        public: true
        arguments: [ '%env(resolve:GEOIP_DIR)%' ]

    Gupalo\GeoIp\Twig\GeoIpExtension:
        public: true
        tags: [ 'twig.extension' ]
        arguments: [ '@Gupalo\GeoIp\GeoIp' ]
